/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(inference.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(19a54979608c15e664fd436c9ff19c9b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <wavelearner/inference.h>
// pydoc.h is automatically generated in the build directory
#include <inference_pydoc.h>

void bind_inference(py::module& m)
{

    using inference    = gr::wavelearner::inference;


    py::class_<inference, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<inference>>(m, "inference", D(inference))

        .def(py::init(&inference::make),
           D(inference,make)
        )
        



        ;




}







